### ISSUE TITLE
Broker failed to start due to different number of Subnets, AZs ang SGs entries 

### ISSUE THREAD

**Issue by Infra-Red** [cloudfoundry-incubator/efsbroker#5]
Hi Team!

EFS broker failed to start in my deployment with the following error:
```
arguments awsSubnetIds, awsAZs, and awsSecurityGroups must have the same number of entries
```

Is there any particular reason to have multiple security groups? Usually single SG that allow all traffic in VPC is enough for deployment. 
https://github.com/cloudfoundry-incubator/efsbroker/blob/b8734837f295a5854628dc3bebbf8d8955aed9c0/cmd/efsbroker/main.go#L220-L222

I can submit a PR if this is something that requires a fix.

Thanks!

**Comment by julian-hj** [comment]
Hi @Infra-Red ,

The basic idea with the multiple security groups is just to allow you to specify multiple AZs, and then for each AZ, to specify the subnet and security group that should be used when establishing a mount point for that AZ.

If you don't have the same number of security groups as AZs, then we don't know what security group to use.

For your use case, where you just want to use the same security group for everything, you should be able to just repeat the same sg name as many times as you have AZs.

Does that make sense?

**Comment by Infra-Red** [comment]
Thanks for the answer @julian-hj !

I see your point, but I still doubt that this shouldn’t be a mandatory requirement. BBL creates a single security group for internal communication and ideally this should be enough to deploy additional services.

I can live with repeating single security group three times, but if we can avoid duplication and still have the same result, then removing such requirement makes sense for me.

**Comment by DennisDenuto** [comment]
Hi @Infra-Red 
Your suggestion is a valid usability enhancement. However this repository is currently under maintenance mode. Meaning that we are only working on security enhancements and/or bug fixes.

Closing this as the original issue has been resolved.
